### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by emrahc** [kritiksoman/GIMP-ML#17]
Hello I wanted to give a try to GIMP-ML but I can't see the menu. I get this error during install
```
    ERROR: Command errored out with exit status 1:
     command: /home/emrah/Code/GIMP-ML/gimp-plugins/gimpenv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54icbb_9/enum/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54icbb_9/enum/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-54icbb_9/enum/pip-egg-info
         cwd: /tmp/pip-install-54icbb_9/enum/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/emrah/Code/GIMP-ML/gimp-plugins/gimpenv/lib/python3.7/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/home/emrah/anaconda3/lib/python3.7/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/home/emrah/anaconda3/lib/python3.7/distutils/dist.py", line 9, in <module>
        import re
      File "/home/emrah/anaconda3/lib/python3.7/re.py", line 143, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

Maybe it confuses due to other packages in my system. Thanks

**Comment by kritiksoman** [comment]
follow INSTALLATION.md

**Comment by Kronosblaster** [comment]
Had this same error with python 3.8. Not with 2.7 though.

**Comment by malcolm1232** [comment]
Hi! Love your work! @kritiksoman ! I'm facing some issue. Under the "Layer" , i dont see GIMP-ML... Wondering why this is so!

I also had the same error of :  AttributeError: module 'enum' has no attribute 'IntFlag' (This occured during installation)

**Comment by daxtas** [comment]
It is not installed in Ubuntu 20.4.1, someone has some solution?  If I change in the script to Python2, the script runs with errors. I tried with the script and manually and can not install it. I think that some changes are needed to run at Ubuntu 20.04 and Python 3.8. I'm just a GIMP user. Does anyone have an idea?

**Comment by gmerrall** [comment]
You can edit installGimpML.sh and change the line
```python -m virtualenv gimpenv```
to 
```python -m virtualenv -p `which python2` gimpenv```

This is because it's likely that the default of "python" now points to python3 and you specifically want python2. There is also a restriction on your version of pip but this might actually get you where you need to go.

**Comment by Fmstrat** [comment]
If the author is waiting for GIMP3 to update to Python3, the installer probably needs to be updated for the latest versions of Ubuntu. If I get time I'll contribute, but I'm not running anything still running on Python 2 on my system at the moment.

**Comment by kritiksoman** [comment]
Working on gimp 3 development now .

**Comment by ramcandrews** [comment]
The problem is that gimp2.10 no longer supports python2. There is no python support in GIMP right now. You can downgrade to 2.08 or wait until GIMP supports python again.

**Comment by kritiksoman** [comment]
https://github.com/kritiksoman/GIMP-ML/tree/GIMP3-ML

**Comment by schumaml** [comment]
> The problem is that gimp2.10 no longer supports python2. There is no python support in GIMP right now. You can downgrade to 2.08 or wait until GIMP supports python again.

GIMP 2.10 supports Python 2 just fine, but some distros have dropped Python 2 and/or some Python modules that are necessary for the GIMP Python modules.

**Comment by joe-eis** [comment]
You should use Gimp from AppStore, this supported Python2. It also nessesary for health repair...
https://appimage.github.io/

**Comment by oberon168** [comment]
I tried install new copy of gimp 2.99.14 and got this when loading.  Also got an error during installing torch 1.8.1

(gimp-2.99.exe:9704): GLib-GIO-WARNING **: 21:02:01.956: win32 session dbus binary not found
set device 'System Aggregated Pointer' to mode: disabled
Skipping potential plug-in 'C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\plugin_utils.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in 'C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\__init__.py': plug-ins must be installed in subdirectories.
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\superresolution\superresolution.py", line 283, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'SuperResolution' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\semseg\semseg.py", line 203, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'SemSeg' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\monodepth\monodepth.py", line 204, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'MonoDepth' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\matting\matting.py", line 223, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Matting' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\kmeans\kmeans.py", line 235, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Kmeans' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\interpolation\interpolation.py", line 279, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Interpolation' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\inpainting\inpainting.py", line 308, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'InPainting' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\filterfolder\filterfolder.py", line 221, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'FilterFolder' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\faceparse\faceparse.py", line 204, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'FaceParse' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\enlighten\enlighten.py", line 203, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Enlighten' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\detectobjects\detectobjects.py", line 196, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'DetectObjects' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\denoise\denoise.py", line 202, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Denoise' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\dehaze\dehaze.py", line 204, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Dehaze' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\deblur\deblur.py", line 205, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Deblur' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\colorpalette\colorpalette.py", line 47, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'ColorPalette' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\coloring\coloring.py", line 253, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Coloring' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "C:\apps\GIMP-ML\gimpenv3\lib\site-packages\gimpml\plugins\canny\canny.py", line 238, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Canny' object has no attribute 'set_translation_domain'

**Comment by Mudassirmuddu** [comment]
> You can edit installGimpML.sh and change the line `python -m virtualenv gimpenv` to `` python -m virtualenv -p `which python2` gimpenv ``
> 
> This is because it's likely that the default of "python" now points to python3 and you specifically want python2. There is also a restriction on your version of pip but this might actually get you where you need to go.

**Comment by Mudassirmuddu** [comment]
Hi, In GIMP I am unable to see Openvino Plugins In layer.

Error : (gimp-2.99.exe:9872): GLib-GIO-WARNING **: 11:59:11.778: win32 session dbus binary not found
set device 'System Aggregated Pointer' to mode: disabled

What the solution can any one hep me in this ?
