### ISSUE TITLE
CUDA out of memory with super-resolution plugin

### ISSUE THREAD

**Issue by YAFU** [kritiksoman/GIMP-ML#20]
System: Kubuntu linux - GTX 960 4GB - Gimp 2.10.18

If I apply Super-resolution plugin to any image larger than about 600x600 px it quickly fills up the 4GB of vRAM and I get the following error:
```
An error occurred running python-fu-super-resolution
RuntimeError: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 0; 3.95 GiB total capacity; 3.10 GiB already allocated; 53.38 MiB free; 3.12 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/home/nulluser/GIMP-ML/gimp-plugins/super_resolution.py", line 100, in super_resolution
    cpy = getnewimg(imgmat,scale)
  File "/home/nulluser/GIMP-ML/gimp-plugins/super_resolution.py", line 56, in getnewimg
    HR_4x = model(im_input)
  File "/home/nulluser/GIMP-ML/gimp-plugins/gimpenv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nulluser/GIMP-ML/gimp-plugins/pytorch-SRResNet/srresnet.py", line 61, in forward
    out = self.residual(out)
  File "/home/nulluser/GIMP-ML/gimp-plugins/gimpenv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nulluser/GIMP-ML/gimp-plugins/gimpenv/lib/python2.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/nulluser/GIMP-ML/gimp-plugins/gimpenv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nulluser/GIMP-ML/gimp-plugins/pytorch-SRResNet/srresnet.py", line 18, in forward
    output = self.in2(self.conv2(output))
  File "/home/nulluser/GIMP-ML/gimp-plugins/gimpenv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nulluser/GIMP-ML/gimp-plugins/gimpenv/lib/python2.7/site-packages/torch/nn/modules/instancenorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/nulluser/GIMP-ML/gimp-plugins/gimpenv/lib/python2.7/site-packages/torch/nn/functional.py", line 1685, in instance_norm
    use_input_stats, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 0; 3.95 GiB total capacity; 3.10 GiB already allocated; 33.44 MiB free; 3.12 GiB reserved in total by PyTorch)
```
As a request derived from this problem, as vRAM capacity can be very varied depending on the users, it would be great if the user could choose between CPU or GPU in the plugins that autodetect CUDA to work.
Thanks!

**Comment by datalot-369** [comment]
I have no measured the vRAM consumption but at least my 4GB system RAM  is not enough for this plugin/filter with medium images (Between 1 and 2 MPx).

I will try with a little image to try to get a replicate.

**Comment by kritiksoman** [comment]
try Force CPU

**Comment by kritiksoman** [comment]
check now (set "Use as filter" to True)

**Comment by datalot-369** [comment]
- Wow, very tricky.
- Can't run `Use as Filter` without `Force CPU`. 
- With a `364 x 264` image and `x4` parameter, it takes my 4GB of RAM but I suspect it has not taken my swap because the program was soft, maybe just background programs did it.
- After a few seconds, I noted changes in the progress bar and finally a new document with the upscaled image raised.
- I'm not sure I could experiment with higher images with this setup (See... 720p), but at the very least it works and is reproducible.

---
Not the best I have seen, for sure:

![original](https://user-images.githubusercontent.com/21994415/97784686-b1528c00-1b76-11eb-9213-c23223f27c21.png)
![upscaled](https://user-images.githubusercontent.com/21994415/97784683-a7c92400-1b76-11eb-80c1-bee04fb70c4d.png)

---

Congratulations to the GIMP ML team!

**Comment by kritiksoman** [comment]
I tried for 1166X672 image on i5 processor, 4gb RAM, macOS. It took 5 minutes to produce 4664X2688 image.
