### ISSUE TITLE
install problem 

### ISSUE THREAD

**Issue by waniah** [kritiksoman/GIMP-ML#45]
Microsoft Windows [Version 10.0.19044.1682]
(c) Microsoft Corporation. Wszelkie prawa zastrzeżone.

(base) C:\Users\wasza>git clone https://github.com/kritiksoman/GIMP-ML.git
'git' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\wasza>conda install git
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\wasza\anaconda3

  added / updated specs:
    - git

The following NEW packages will be INSTALLED:

  git                pkgs/main/win-64::git-2.34.1-haa95532_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Users\wasza>git clone https://github.com/kritiksoman/GIMP-ML.git
Cloning into 'GIMP-ML'...
remote: Enumerating objects: 2457, done.
remote: Counting objects: 100% (184/184), done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 2457 (delta 72), reused 154 (delta 51), pack-reused 2273 eceiving objects: 100% (2457/2457), 112.67 MiB | Receiving objects: 100% (2457/2457), 115.57 MiB | 4.64 MiB/s, done.

Resolving deltas: 100% (1176/1176), done.

(base) C:\Users\wasza>git checkout --track origin/GIMP3-ML
fatal: not a git repository (or any of the parent directories): .git

(base) C:\Users\wasza>cd C:\Users\wasza\GIMP-ML

(base) C:\Users\wasza\GIMP-ML>git checkout --track origin/GIMP3-ML
Switched to a new branch 'GIMP3-ML'
Branch 'GIMP3-ML' set up to track remote branch 'GIMP3-ML' from 'origin'.

(base) C:\Users\wasza\GIMP-ML>

(base) C:\Users\wasza\GIMP-ML>install.bat gpu
**** GIMP-ML Setup started ****
Collecting virtualenv
  Downloading virtualenv-20.14.1-py2.py3-none-any.whl (8.8 MB)
     |████████████████████████████████| 8.8 MB 1.7 MB/s
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.4-py2.py3-none-any.whl (461 kB)
     |████████████████████████████████| 461 kB ...
Requirement already satisfied: filelock<4,>=3.2 in c:\users\wasza\anaconda3\lib\site-packages (from virtualenv) (3.3.1)
Requirement already satisfied: six<2,>=1.9.0 in c:\users\wasza\anaconda3\lib\site-packages (from virtualenv) (1.16.0)
Collecting platformdirs<3,>=2
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Installing collected packages: platformdirs, distlib, virtualenv
Successfully installed distlib-0.3.4 platformdirs-2.5.2 virtualenv-20.14.1
created virtual environment CPython3.9.7.final.0-64 in 3494ms
  creator CPython3Windows(dest=C:\Users\wasza\GIMP-ML\gimpenv3, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\wasza\AppData\Local\pypa\virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Collecting torch==1.8.1+cu111
  Using cached https://download.pytorch.org/whl/lts/1.8/cu111/torch-1.8.1%2Bcu111-cp39-cp39-win_amd64.whl (3055.6 MB)
Collecting torchvision==0.9.1+cu111
  Using cached https://download.pytorch.org/whl/lts/1.8/cu111/torchvision-0.9.1%2Bcu111-cp39-cp39-win_amd64.whl (1.9 MB)
Collecting torchaudio===0.8.1
  Downloading torchaudio-0.8.1-cp39-none-win_amd64.whl (109 kB)
     ---------------------------------------- 109.3/109.3 KB 1.6 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting numpy
  Downloading numpy-1.22.3-cp39-cp39-win_amd64.whl (14.7 MB)
     ---------------------------------------- 14.7/14.7 MB 25.1 MB/s eta 0:00:00
Collecting pillow>=4.1.1
  Downloading Pillow-9.1.0-cp39-cp39-win_amd64.whl (3.3 MB)
     ---------------------------------------- 3.3/3.3 MB 26.0 MB/s eta 0:00:00
Installing collected packages: typing-extensions, pillow, numpy, torch, torchvision, torchaudio
Successfully installed numpy-1.22.3 pillow-9.1.0 torch-1.8.1+cu111 torchaudio-0.8.1 torchvision-0.9.1+cu111 typing-extensions-4.2.0
ERROR: Invalid requirement: 'GIMP-ML\\.'
Hint: It looks like a path. File 'GIMP-ML\.' does not exist.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\wasza\GIMP-ML\gimpml\__init__.py", line 1, in <module>
    from .tools.kmeans import get_kmeans as kmeans
  File "C:\Users\wasza\GIMP-ML\gimpml\tools\kmeans.py", line 4, in <module>
    from scipy.cluster.vq import kmeans2
ModuleNotFoundError: No module named 'scipy'
**** GIMP-ML Setup Ended ****

(base) C:\Users\wasza\GIMP-ML>

**Comment by leesongun** [comment]
You need to run the script from one directory up, that is `C:\Users\wasza`. Hope this helps!
