### ISSUE TITLE
GIMP 2.10.32 does not execute the GIMP-ML plugins

### ISSUE THREAD

**Issue by phenrypereira** [kritiksoman/GIMP-ML#51]
**Describe the bug**
After installation complete I saw that GIMP-ML does not show up in Layer menu.
So I run GIMP in Terminal and :
$ gimp

(gimp:77933): Gtk-WARNING **: 20:08:10.900: Não foi possível localizar a ferramenta de temas no module_path: "adwaita",

(gimp:77933): Gtk-WARNING **: 20:08:11.248: Theme directory places/128 of theme ubuntustudio-dark has no size field

(gimp:77933): Gtk-WARNING **: 20:08:11.248: Theme directory places/scalable of theme ubuntustudio-dark has no size field

Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/update.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/syncWeights.py", line 1, in <module>
    import requests
ImportError: No module named requests
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/super_resolution.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/semseg.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/monodepth.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/kmeans.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/invert.py", line 2, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/interpolateframes.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/inpainting.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/faceparse.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/facegen.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/enlighten.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/deepmatting.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/deepdenoise.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/deepdehaze.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/deepcolor.py", line 3, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/deblur.py", line 5, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/Documentos/GIMP-ML/gimp-plugins/colorpalette.py", line 3, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error

Usage:   
  get-pip.py install [options] <requirement specifier> [package-index-options] ...
  get-pip.py install [options] -r <requirements file> [package-index-options] ...
  get-pip.py install [options] [-e] <vcs project url> ...
  get-pip.py install [options] [-e] <local project path> ...
  get-pip.py install [options] <archive url/path> ...

no such option: -g
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/python-eval/python-eval.py", line 19, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/python-console/python-console.py", line 19, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/py-slice/py-slice.py", line 30, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/palette-to-gradient/palette-to-gradient.py", line 16, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/palette-sort/palette-sort.py", line 17, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/palette-offset/palette-offset.py", line 16, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/histogram-export/histogram-export.py", line 40, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/gradients-save-as-css/gradients-save-as-css.py", line 25, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/foggify/foggify.py", line 19, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/file-openraster/file-openraster.py", line 20, in <module>
    from gimpfu import *
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/colorxhtml/colorxhtml.py", line 24, in <module>
    import gimp
ImportError: could not import pygtk
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/phenry/.config/GIMP/2.10/plug-ins/remove_background.py", line 7, in <module>
    import requests
ImportError: No module named requests
gimp: LibGimpBase-- AVISO: gimp: gimp_wire_read(): error
Plug-in "script-fu"
(/usr/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-bw-film" with a full menu path "<Image>/Colors/BW Film Simulation" as menu label, this deprecated and will be an error in GIMP 3.0
Plug-in "script-fu"
(/usr/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-selection-to-anim-image" with a full menu path "<Image>/Filters/Animation/Animators/Selection to AnimImage..." as menu label, this deprecated and will be an error in GIMP 3.0
Plug-in "script-fu"
(/usr/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "diana-holga2c" with a full menu path "<Image>/Filters/Artistic/diana-holga2b" as menu label, this deprecated and will be an error in GIMP 3.0
Plug-in "script-fu"
(/usr/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-draw-arch" with a full menu path "<Image>/FX-Foundry/Shapes/Parametric/_Arch" as menu label, this deprecated and will be an error in GIMP 3.0
Plug-in "script-fu"
(/usr/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-draw-box" with a full menu path "<Image>/FX-Foundry/Shapes/Parametric/Box" as menu label, this deprecated and will be an error in GIMP 3.0
Plug-in "script-fu"
(/usr/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-draw-ellipse" with a full menu path "<Image>/FX-Foundry/Shapes/Parametric/Ellipse" as menu label, this deprecated and will be an error in GIMP 3.0
Plug-in "script-fu"
(/usr/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-gap-dup-continue" with a full menu path "<Image>/Video/Duplicate Continue" as menu label, this deprecated and will be an error in GIMP 3.0

I don't know what exactly it means, but something still feels wrong.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Ubuntu Studio 22.04.01
 - GIMP Version: 2.10.32

**Comment by dovezp** [comment]
Download the developer version: https://www.gimp.org/downloads/devel/

**Comment by mikewesten** [comment]
@dove-zp Do you mean to say GIMP-ML does not work with the stable (current) version of GIMP? At all?

**Comment by dovezp** [comment]
> [@dove-zp](https://github.com/dove-zp) Do you mean to say GIMP-ML does not work with the stable (current) version of GIMP? At all?

Read the print of https://kritiksoman.github.io/GIMP-ML-Docs/docs-page.html, was based off the development version starting from 2.99 which was the development release. Now gimp 3 is the stable release. 

The author of this issue was using gimp 2.10 which does not have the same functionality as 2.99+
