### ISSUE TITLE
Gimp ML not in Layer menu, Linux Mint 21 Cinnamon

### ISSUE THREAD

**Issue by GawainProdigy** [kritiksoman/GIMP-ML#53]
I followed all of the steps and successfully installed everything, but ml not showing up in 'layer' menu.

The only snag I saw during the process was this bit that flew by during the installation: Gimp ML/GIMP-ML/get-pip.py': [Errno 2] No such file or directory.

I copied the plug-in path, as shown in video, and was displayed in my terminal at the end of the installation process, yet no GIMP-ML.

I realize this might not be a clear enough place to start for you, but that's all I have so far. Your help and follow-up would be appreciated. Thanks a lot.

**Comment by NachoPicchu** [comment]
Open a terminal and start "gimp" through that.
You will likely get output along the lines of 
`Gtk-Message: 18:35:06.168: Failed to load module "appmenu-gtk-module"
Traceback (most recent call last):
File "/home/user/gimpenv3/lib/python3.11/site-packages/gimpml/plugins/superresolution/superresolution.py", line 283, in do_query_procedures
self.set_translation_domain(
^^^^^^^^^^^^^^^^^^^^^^^^^^^`

Follow the advice from the answer [here](https://stackoverflow.com/questions/73466260/trouble-getting-gimp-plugins-to-work-python-attribute-missing)
Meaning, go to the plugin folder and edit the corresponding .py file as instructed.

**Comment by xXPerditorXx** [comment]
I don't even get an error message and I have the same problem
Archlinux 6.3.5 and KDE 5.27.5

Got this error:
```
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/plugin_utils.py", line 2, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python2.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
```
