### ISSUE TITLE
GIMP cannot import GIMP-ML

### ISSUE THREAD

**Issue by szmarczak** [kritiksoman/GIMP-ML#58]
**Describe the bug**

```
gimp
This is a development version of GIMP.  Debug messages may appear here.

set device 'Logitech G102 Prodigy Gaming Mouse Keyboard' to mode: disabled
set device 'Logitech G102 Prodigy Gaming Mouse' to mode: disabled
set device 'Razer Razer BlackWidow Chroma V2' to mode: disabled
set device 'Virtual core XTEST pointer' to mode: disabled
set device 'Razer Razer BlackWidow Chroma V2 Keyboard' to mode: disabled
Skipping potential plug-in '/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/__init__.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/plugin_utils.py': plug-ins must be installed in subdirectories.
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/monodepth/monodepth.py", line 204, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'MonoDepth' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/inpainting/inpainting.py", line 308, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'InPainting' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/enlighten/enlighten.py", line 203, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Enlighten' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/deblur/deblur.py", line 205, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Deblur' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/matting/matting.py", line 223, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Matting' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/detectobjects/detectobjects.py", line 196, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'DetectObjects' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/colorpalette/colorpalette.py", line 47, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'ColorPalette' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/superresolution/superresolution.py", line 283, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'SuperResolution' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/filterfolder/filterfolder.py", line 221, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'FilterFolder' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/denoise/denoise.py", line 202, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Denoise' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/coloring/coloring.py", line 253, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Coloring' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/kmeans/kmeans.py", line 235, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Kmeans' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/semseg/semseg.py", line 203, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'SemSeg' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/faceparse/faceparse.py", line 204, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'FaceParse' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/dehaze/dehaze.py", line 204, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Dehaze' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/canny/canny.py", line 238, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Canny' object has no attribute 'set_translation_domain'
Traceback (most recent call last):
  File "/home/szm/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/interpolation/interpolation.py", line 279, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Interpolation' object has no attribute 'set_translation_domain'
luajit: .../org.gimp.extension.goat-exercises/goat-exercise-lua.lua:22: module 'lgi' not found:
	no field package.preload['lgi']
	no file './lgi.lua'
	no file '/usr/share/luajit-2.1.0-beta3/lgi.lua'
	no file '/usr/local/share/lua/5.1/lgi.lua'
	no file '/usr/local/share/lua/5.1/lgi/init.lua'
	no file '/usr/share/lua/5.1/lgi.lua'
	no file '/usr/share/lua/5.1/lgi/init.lua'
	no file './lgi.so'
	no file '/usr/local/lib/lua/5.1/lgi.so'
	no file '/usr/lib/lua/5.1/lgi.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	.../org.gimp.extension.goat-exercises/goat-exercise-lua.lua:22: in main chunk
	[C]: at 0x563cc50cdcd0
GIMP-WARNING: gimp: gimp_wire_read(): error

/usr/bin/env: ‘gjs’: No such file or directory
GIMP-WARNING: gimp: gimp_wire_read(): error
```

**To Reproduce**

Follow the install instructions on Arch Linux (GIMP 2.99).

**Comment by szmarczak** [comment]
If anyone stumbles upon this, here's the fix: https://stackoverflow.com/a/73484432

**Comment by SSamiK** [comment]
Yeah, I have the same error multiple times. 

```

Gtk-Message: 19:08:19.264: Failed to load module "xapp-gtk3-module"
This is a development version of GIMP.  Debug messages may appear here.

set device 'USB Optical Mouse' to mode: disabled
set device 'Virtual core XTEST pointer' to mode: disabled
set device 'AlpsPS/2 ALPS DualPoint Stick' to mode: disabled
set device 'AlpsPS/2 ALPS DualPoint TouchPad' to mode: disabled
Skipping potential plug-in '/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/__init__.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/plugin_utils.py': plug-ins must be installed in subdirectories.
Gtk-Message: 19:08:20.408: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/superresolution/superresolution.py", line 283, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'SuperResolution' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:20.584: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/semseg/semseg.py", line 203, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'SemSeg' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:20.762: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/monodepth/monodepth.py", line 204, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'MonoDepth' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:20.939: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/matting/matting.py", line 223, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Matting' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:21.114: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/kmeans/kmeans.py", line 235, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Kmeans' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:21.293: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/interpolation/interpolation.py", line 279, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Interpolation' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:21.482: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/inpainting/inpainting.py", line 308, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'InPainting' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:21.661: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/filterfolder/filterfolder.py", line 221, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'FilterFolder' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:21.838: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/faceparse/faceparse.py", line 204, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'FaceParse' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:22.034: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/enlighten/enlighten.py", line 203, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Enlighten' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:22.228: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/detectobjects/detectobjects.py", line 196, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'DetectObjects' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:22.403: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/denoise/denoise.py", line 202, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Denoise' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:22.581: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/dehaze/dehaze.py", line 204, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Dehaze' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:22.757: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/deblur/deblur.py", line 205, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Deblur' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:22.931: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/colorpalette/colorpalette.py", line 47, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'ColorPalette' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:23.110: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/coloring/coloring.py", line 253, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Coloring' object has no attribute 'set_translation_domain'
Gtk-Message: 19:08:23.286: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/home/ssamik/gimpenv3/lib/python3.10/site-packages/gimpml/plugins/canny/canny.py", line 238, in do_query_procedures
    self.set_translation_domain(
AttributeError: 'Canny' object has no attribute 'set_translation_domain'


```
