### ISSUE TITLE
Error During Install 

### ISSUE THREAD

**Issue by mybigbadself** [kritiksoman/GIMP-ML#68]
Windows 10
GIMP 2.99.6 Installed
Python 3.11.4

Followed the instructions on the install. 

After running Install.bat I get the following error. 

ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cpu (from versions: 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cu117, 2.0.1+cu118, 2.1.0, 2.1.0+cpu, 2.1.0+cu118, 2.1.0+cu121)             ERROR: No matching distribution found for torch==1.8.1+cpu                                                              ERROR: Invalid requirement: 'GIMP-ML\\.'                                                                                Hint: It looks like a path. File 'GIMP-ML\.' does not exist. 

I also have a stable version of GIMP installed 2.10.34

**Comment by mybigbadself** [comment]
tried on a clean install of Windows 11 and got the same error. after running install.bat. 

ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cpu (from versions: 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cu117, 2.0.1+cu118, 2.1.0, 2.1.0+cpu, 2.1.0+cu118, 2.1.0+cu121)
ERROR: No matching distribution found for torch==1.8.1+cpu
ERROR: Invalid requirement: 'GIMP-ML\\.'
Hint: It looks like a path. File 'GIMP-ML\.' does not exist.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mccab\Documents\GIMP-ML\gimpml\__init__.py", line 1, in <module>
    from .tools.kmeans import get_kmeans as kmeans
  File "C:\Users\mccab\Documents\GIMP-ML\gimpml\tools\kmeans.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
**** GIMP-ML Setup Ended ****

**Comment by DRB-Ecovium** [comment]
Use Python 3.8 and it will work.
![image](https://github.com/kritiksoman/GIMP-ML/assets/109788505/12a6563e-b71e-4c37-bbd7-5a578b5e4976)

**Comment by bmmtstb** [comment]
In the end, the ``install.bat`` wants to install the git project. But I struggled with the automatic version as well. It seems we should run everything from the parent directory. But just running (in the environment!) ``pip install .`` to install the ``setup.py`` works perfectly fine.
